export const courseCategories = [
  {
    'id': 1,
    'left': 1,
    'right': 10000001,
    'depth': 0,
    'name': 'LANGUAGES',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 2,
    'left': 3,
    'right': 100003,
    'depth': 1,
    'name': 'ENGLISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 3,
    'left': 5,
    'right': 1005,
    'depth': 2,
    'name': 'GENERAL_ENGLISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 4,
    'left': 1006,
    'right': 2006,
    'depth': 2,
    'name': 'BUSINESS_ENGLISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 5,
    'left': 2007,
    'right': 3007,
    'depth': 2,
    'name': 'ACADEMIC_ENGLISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 6,
    'left': 3008,
    'right': 4008,
    'depth': 2,
    'name': 'EXAM_PREPARATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 7,
    'left': 4009,
    'right': 5009,
    'depth': 2,
    'name': 'PROFESSIONAL_AND_EXECUTIVE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 8,
    'left': 5010,
    'right': 6010,
    'depth': 2,
    'name': 'TEACHER_TRAINING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 9,
    'left': 6011,
    'right': 7011,
    'depth': 2,
    'name': 'WORK_AND_STUDY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 10,
    'left': 7012,
    'right': 8012,
    'depth': 2,
    'name': 'ENGLISH_PLUS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 11,
    'left': 8013,
    'right': 9013,
    'depth': 2,
    'name': 'JUNIOR_PROGRAM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 12,
    'left': 100004,
    'right': 200004,
    'depth': 1,
    'name': 'SPANISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 13,
    'left': 200005,
    'right': 300005,
    'depth': 1,
    'name': 'CHINESE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 14,
    'left': 10000002,
    'right': 20000002,
    'depth': 0,
    'name': 'VOCATIONAL',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 15,
    'left': 20000003,
    'right': 30000003,
    'depth': 0,
    'name': 'HIGHSCHOOL',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 16,
    'left': 30000004,
    'right': 40000004,
    'depth': 0,
    'name': 'HIGHER_EDUCATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 17,
    'left': 30000006,
    'right': 30100006,
    'depth': 1,
    'name': 'UNDERGRADUATE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 18,
    'left': 30100007,
    'right': 30200007,
    'depth': 1,
    'name': 'GRADUATE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 19,
    'left': 30200008,
    'right': 30300008,
    'depth': 1,
    'name': 'CERTIFICATE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 20,
    'left': 40000007,
    'right': 40100007,
    'depth': 1,
    'name': 'OTHER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 21,
    'left': 100006,
    'right': 101006,
    'depth': 2,
    'name': 'GENERAL_SPANISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 22,
    'left': 101007,
    'right': 102007,
    'depth': 2,
    'name': 'BUSINESS_SPANISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 23,
    'left': 102008,
    'right': 103008,
    'depth': 2,
    'name': 'ACADEMIC_SPANISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 24,
    'left': 103009,
    'right': 104009,
    'depth': 2,
    'name': 'EXAM_PREPARATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 25,
    'left': 104010,
    'right': 105010,
    'depth': 2,
    'name': 'PROFESSIONAL_AND_EXECUTIVE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 26,
    'left': 105011,
    'right': 106011,
    'depth': 2,
    'name': 'TEACHER_TRAINING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 27,
    'left': 106012,
    'right': 107012,
    'depth': 2,
    'name': 'WORK_AND_STUDY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 28,
    'left': 107013,
    'right': 108013,
    'depth': 2,
    'name': 'SPANISH_PLUS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 29,
    'left': 108014,
    'right': 109014,
    'depth': 2,
    'name': 'JUNIOR_PROGRAM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 30,
    'left': 200007,
    'right': 201007,
    'depth': 2,
    'name': 'GENERAL_CHINESE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 31,
    'left': 201008,
    'right': 202008,
    'depth': 2,
    'name': 'BUSINESS_CHINESE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 32,
    'left': 202009,
    'right': 203009,
    'depth': 2,
    'name': 'ACADEMIC_CHINESE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 33,
    'left': 203010,
    'right': 204010,
    'depth': 2,
    'name': 'EXAM_PREPARATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 34,
    'left': 204011,
    'right': 205011,
    'depth': 2,
    'name': 'PROFESSIONAL_AND_EXECUTIVE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 35,
    'left': 205012,
    'right': 206012,
    'depth': 2,
    'name': 'TEACHER_TRAINING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 36,
    'left': 206013,
    'right': 207013,
    'depth': 2,
    'name': 'WORK_AND_STUDY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 37,
    'left': 207014,
    'right': 208014,
    'depth': 2,
    'name': 'CHINESE_PLUS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 38,
    'left': 208015,
    'right': 209015,
    'depth': 2,
    'name': 'JUNIOR_PROGRAM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 39,
    'left': 300006,
    'right': 400006,
    'depth': 1,
    'name': 'FRENCH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 40,
    'left': 300008,
    'right': 301008,
    'depth': 2,
    'name': 'GENERAL_FRENCH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 41,
    'left': 301009,
    'right': 302009,
    'depth': 2,
    'name': 'BUSINESS_FRENCH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 42,
    'left': 302010,
    'right': 303010,
    'depth': 2,
    'name': 'ACADEMIC_FRENCH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 43,
    'left': 303011,
    'right': 304011,
    'depth': 2,
    'name': 'EXAM_PREPARATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 44,
    'left': 304012,
    'right': 305012,
    'depth': 2,
    'name': 'PROFESSIONAL_AND_EXECUTIVE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 45,
    'left': 305013,
    'right': 306013,
    'depth': 2,
    'name': 'TEACHER_TRAINING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 46,
    'left': 306014,
    'right': 307014,
    'depth': 2,
    'name': 'WORK_AND_STUDY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 47,
    'left': 307015,
    'right': 308015,
    'depth': 2,
    'name': 'FRENCH_PLUS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 48,
    'left': 308016,
    'right': 309016,
    'depth': 2,
    'name': 'JUNIOR_PROGRAM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 49,
    'left': 400007,
    'right': 500007,
    'depth': 1,
    'name': 'GERMAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 50,
    'left': 400009,
    'right': 401009,
    'depth': 2,
    'name': 'GENERAL_GERMAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 51,
    'left': 401010,
    'right': 402010,
    'depth': 2,
    'name': 'BUSINESS_GERMAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 52,
    'left': 402011,
    'right': 403011,
    'depth': 2,
    'name': 'ACADEMIC_GERMAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 53,
    'left': 403012,
    'right': 404012,
    'depth': 2,
    'name': 'EXAM_PREPARATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 54,
    'left': 404013,
    'right': 405013,
    'depth': 2,
    'name': 'PROFESSIONAL_AND_EXECUTIVE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 55,
    'left': 405014,
    'right': 406014,
    'depth': 2,
    'name': 'TEACHER_TRAINING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 56,
    'left': 406015,
    'right': 407015,
    'depth': 2,
    'name': 'WORK_AND_STUDY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 57,
    'left': 407016,
    'right': 408016,
    'depth': 2,
    'name': 'GERMAN_PLUS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 58,
    'left': 408017,
    'right': 409017,
    'depth': 2,
    'name': 'JUNIOR_PROGRAM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 59,
    'left': 500008,
    'right': 600008,
    'depth': 1,
    'name': 'ITALIAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 60,
    'left': 500010,
    'right': 501010,
    'depth': 2,
    'name': 'GENERAL_ITALIAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 61,
    'left': 501011,
    'right': 502011,
    'depth': 2,
    'name': 'BUSINESS_ITALIAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 62,
    'left': 502012,
    'right': 503012,
    'depth': 2,
    'name': 'ACADEMIC_ITALIAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 63,
    'left': 503013,
    'right': 504013,
    'depth': 2,
    'name': 'EXAM_PREPARATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 64,
    'left': 504014,
    'right': 505014,
    'depth': 2,
    'name': 'PROFESSIONAL_AND_EXECUTIVE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 65,
    'left': 505015,
    'right': 506015,
    'depth': 2,
    'name': 'TEACHER_TRAINING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 66,
    'left': 506016,
    'right': 507016,
    'depth': 2,
    'name': 'WORK_AND_STUDY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 67,
    'left': 507017,
    'right': 508017,
    'depth': 2,
    'name': 'ITALIAN_PLUS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 68,
    'left': 508018,
    'right': 509018,
    'depth': 2,
    'name': 'JUNIOR_PROGRAM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 69,
    'left': 20000005,
    'right': 20100005,
    'depth': 1,
    'name': 'PUBLIC',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 70,
    'left': 20100006,
    'right': 20200006,
    'depth': 1,
    'name': 'PRIVATE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 71,
    'left': 30300009,
    'right': 30400009,
    'depth': 1,
    'name': 'DIPLOMA',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 72,
    'left': 30400010,
    'right': 30500010,
    'depth': 1,
    'name': 'POST_GRADUATE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 73,
    'left': 30500011,
    'right': 30600011,
    'depth': 1,
    'name': 'MASTERS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 74,
    'left': 30600012,
    'right': 30700012,
    'depth': 1,
    'name': 'PHD',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 75,
    'left': 600009,
    'right': 700009,
    'depth': 1,
    'name': 'PORTUGUESE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 76,
    'left': 600011,
    'right': 601011,
    'depth': 2,
    'name': 'GENERAL_PORTUGUESE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 77,
    'left': 601012,
    'right': 602012,
    'depth': 2,
    'name': 'BUSINESS_PORTUGUESE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 78,
    'left': 602013,
    'right': 603013,
    'depth': 2,
    'name': 'ACADEMIC_PORTUGUESE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 79,
    'left': 603014,
    'right': 604014,
    'depth': 2,
    'name': 'EXAM_PREPARATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 80,
    'left': 604015,
    'right': 605015,
    'depth': 2,
    'name': 'PROFESSIONAL_AND_EXECUTIVE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 81,
    'left': 605016,
    'right': 606016,
    'depth': 2,
    'name': 'TEACHER_TRAINING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 82,
    'left': 606017,
    'right': 607017,
    'depth': 2,
    'name': 'WORK_AND_STUDY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 83,
    'left': 607018,
    'right': 608018,
    'depth': 2,
    'name': 'PORTUGUESE_PLUS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 84,
    'left': 608019,
    'right': 609019,
    'depth': 2,
    'name': 'JUNIOR_PROGRAM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 85,
    'left': 9014,
    'right': 10014,
    'depth': 2,
    'name': 'MATURE_LEARNER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 86,
    'left': 109015,
    'right': 110015,
    'depth': 2,
    'name': 'MATURE_LEARNER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 87,
    'left': 209016,
    'right': 210016,
    'depth': 2,
    'name': 'MATURE_LEARNER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 88,
    'left': 309017,
    'right': 310017,
    'depth': 2,
    'name': 'MATURE_LEARNER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 89,
    'left': 409018,
    'right': 410018,
    'depth': 2,
    'name': 'MATURE_LEARNER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 90,
    'left': 509019,
    'right': 510019,
    'depth': 2,
    'name': 'MATURE_LEARNER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 91,
    'left': 700010,
    'right': 800010,
    'depth': 1,
    'name': 'KOREAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 92,
    'left': 700012,
    'right': 701012,
    'depth': 2,
    'name': 'GENERAL_KOREAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 93,
    'left': 701013,
    'right': 702013,
    'depth': 2,
    'name': 'BUSINESS_KOREAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 94,
    'left': 702014,
    'right': 703014,
    'depth': 2,
    'name': 'ACADEMIC_KOREAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 95,
    'left': 703015,
    'right': 704015,
    'depth': 2,
    'name': 'EXAM_PREPARATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 96,
    'left': 704016,
    'right': 705016,
    'depth': 2,
    'name': 'PROFESSIONAL_AND_EXECUTIVE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 97,
    'left': 705017,
    'right': 706017,
    'depth': 2,
    'name': 'TEACHER_TRAINING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 98,
    'left': 706018,
    'right': 707018,
    'depth': 2,
    'name': 'WORK_AND_STUDY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 99,
    'left': 707019,
    'right': 708019,
    'depth': 2,
    'name': 'KOREAN_PLUS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 100,
    'left': 708020,
    'right': 709020,
    'depth': 2,
    'name': 'JUNIOR_PROGRAM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 101,
    'left': 709021,
    'right': 710021,
    'depth': 2,
    'name': 'MATURE_LEARNER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 102,
    'left': 10000004,
    'right': 10100004,
    'depth': 1,
    'name': 'AVIATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 103,
    'left': 10100005,
    'right': 10200005,
    'depth': 1,
    'name': 'ACCOUNTING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 104,
    'left': 10200006,
    'right': 10300006,
    'depth': 1,
    'name': 'AGED_CARE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 105,
    'left': 10300007,
    'right': 10400007,
    'depth': 1,
    'name': 'AMC_CLINICAL_AND_PESCI_PREP',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 106,
    'left': 10400008,
    'right': 10500008,
    'depth': 1,
    'name': 'ANIMAL_CARE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 107,
    'left': 10500009,
    'right': 10600009,
    'depth': 1,
    'name': 'AUTOMOTIVE_STUDIES',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 108,
    'left': 10600010,
    'right': 10700010,
    'depth': 1,
    'name': 'SCIENCE_AND_ENGINEERING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 109,
    'left': 10600012,
    'right': 10601012,
    'depth': 2,
    'name': 'BUILDING_CONSTRUCTION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 110,
    'left': 10601013,
    'right': 10602013,
    'depth': 2,
    'name': 'ENGINEERING_STUDIES',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 111,
    'left': 10602014,
    'right': 10603014,
    'depth': 2,
    'name': 'ENVIRONMENTAL_SCIENCES',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 112,
    'left': 10700011,
    'right': 10800011,
    'depth': 1,
    'name': 'BUSINESS_MANAGEMENT',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 113,
    'left': 10701014,
    'right': 10702014,
    'depth': 2,
    'name': 'MARKETING_AND_ADVERTISING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 114,
    'left': 10702015,
    'right': 10703015,
    'depth': 2,
    'name': 'FINANCE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 115,
    'left': 10800012,
    'right': 10900012,
    'depth': 1,
    'name': 'CHILDREN_SERVICES',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 116,
    'left': 10900013,
    'right': 11000013,
    'depth': 1,
    'name': 'HEALTH_SERVICES',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 117,
    'left': 11000014,
    'right': 11100014,
    'depth': 1,
    'name': 'HORTICULTURE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 118,
    'left': 11100015,
    'right': 11200015,
    'depth': 1,
    'name': 'ART_DIGITAL_MEDIA_AND_DESIGN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 119,
    'left': 11100017,
    'right': 11101017,
    'depth': 2,
    'name': 'FINE_ARTS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 120,
    'left': 11101018,
    'right': 11102018,
    'depth': 2,
    'name': 'DESIGN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 121,
    'left': 11102019,
    'right': 11103019,
    'depth': 2,
    'name': 'GRAPHIC_DESIGN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 122,
    'left': 11103020,
    'right': 11104020,
    'depth': 2,
    'name': 'DIGITAL_MEDIA',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 123,
    'left': 11104021,
    'right': 11105021,
    'depth': 2,
    'name': 'PHOTOGRAPHY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 124,
    'left': 11105022,
    'right': 11106022,
    'depth': 2,
    'name': 'INTERIOR_DESIGN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 125,
    'left': 11106023,
    'right': 11107023,
    'depth': 2,
    'name': 'ANIMATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 126,
    'left': 11107024,
    'right': 11108024,
    'depth': 2,
    'name': 'GAMING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 127,
    'left': 11108025,
    'right': 11109025,
    'depth': 2,
    'name': 'FILM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 128,
    'left': 11200016,
    'right': 11300016,
    'depth': 1,
    'name': 'FASHION_AND_BEAUTY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 129,
    'left': 11200018,
    'right': 11201018,
    'depth': 2,
    'name': 'FASHION_DESIGN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 130,
    'left': 11201019,
    'right': 11202019,
    'depth': 2,
    'name': 'FASHION_MERCHANDISING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 131,
    'left': 11202020,
    'right': 11203020,
    'depth': 2,
    'name': 'JEWELLERY_DESIGN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 132,
    'left': 11203021,
    'right': 11204021,
    'depth': 2,
    'name': 'BEAUTY_AND_AESTHETICIAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 133,
    'left': 11300017,
    'right': 11400017,
    'depth': 1,
    'name': 'HUMAN_RESOURCES',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 134,
    'left': 11400018,
    'right': 11500018,
    'depth': 1,
    'name': 'MASSAGE_THERAPY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 135,
    'left': 11500019,
    'right': 11600019,
    'depth': 1,
    'name': 'MUSIC_STUDIES',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 136,
    'left': 11600020,
    'right': 11700020,
    'depth': 1,
    'name': 'OCCUPATIONAL_HEALTH_AND_SAFETY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 137,
    'left': 11700021,
    'right': 11800021,
    'depth': 1,
    'name': 'SPORTS_AND_FITNESS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 138,
    'left': 11800022,
    'right': 11900022,
    'depth': 1,
    'name': 'THEOLOGY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 139,
    'left': 11900023,
    'right': 12000023,
    'depth': 1,
    'name': 'HOSPITALITY_AND_TOURISM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 140,
    'left': 11900025,
    'right': 11901025,
    'depth': 2,
    'name': 'HOSPITALITY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 141,
    'left': 11901026,
    'right': 11902026,
    'depth': 2,
    'name': 'TOURISM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 142,
    'left': 11902027,
    'right': 11903027,
    'depth': 2,
    'name': 'CULINARY_STUDIES',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 143,
    'left': 11903028,
    'right': 11904028,
    'depth': 2,
    'name': 'EVENTS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 144,
    'left': 12000024,
    'right': 12100024,
    'depth': 1,
    'name': 'TRAINING_ASSESSMENT',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 145,
    'left': 12100025,
    'right': 12200025,
    'depth': 1,
    'name': 'TECHNOLOGY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 146,
    'left': 12100027,
    'right': 12101027,
    'depth': 2,
    'name': 'INFORMATION_TECHNOLOGY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 147,
    'left': 12101028,
    'right': 12102028,
    'depth': 2,
    'name': 'TELECOMMUNICATIONS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 148,
    'left': 12102029,
    'right': 12103029,
    'depth': 2,
    'name': 'PROGRAMMING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 149,
    'left': 10703016,
    'right': 10704016,
    'depth': 2,
    'name': 'PROJECT_MANAGEMENT',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 150,
    'left': 10704017,
    'right': 10705017,
    'depth': 2,
    'name': 'LEADERSHIP_AND_MANAGEMENT',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 151,
    'left': 10700013,
    'right': 10701013,
    'depth': 2,
    'name': 'BUSINESS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 152,
    'left': 40000005,
    'right': 50000005,
    'depth': 0,
    'name': 'OTHER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 153,
    'left': 12200026,
    'right': 12300026,
    'depth': 1,
    'name': 'TRANSLATION_AND_INTERPRETATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 154,
    'left': 800011,
    'right': 900011,
    'depth': 1,
    'name': 'RUSSIAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 155,
    'left': 800013,
    'right': 801013,
    'depth': 2,
    'name': 'GENERAL_RUSSIAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 156,
    'left': 801014,
    'right': 802014,
    'depth': 2,
    'name': 'BUSINESS_RUSSIAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 157,
    'left': 802015,
    'right': 803015,
    'depth': 2,
    'name': 'ACADEMIC_RUSSIAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 158,
    'left': 803016,
    'right': 804016,
    'depth': 2,
    'name': 'EXAM_PREPARATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 159,
    'left': 804017,
    'right': 805017,
    'depth': 2,
    'name': 'UNIVERSITY_PATHWAY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 160,
    'left': 805018,
    'right': 806018,
    'depth': 2,
    'name': 'TEACHER_TRAINING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 161,
    'left': 806019,
    'right': 807019,
    'depth': 2,
    'name': 'WORK_AND_STUDY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 162,
    'left': 807020,
    'right': 808020,
    'depth': 2,
    'name': 'RUSSIAN_PLUS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 163,
    'left': 808021,
    'right': 809021,
    'depth': 2,
    'name': 'JUNIOR_PROGRAM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 164,
    'left': 809022,
    'right': 810022,
    'depth': 2,
    'name': 'MATURE_LEARNER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 165,
    'left': 900012,
    'right': 1000012,
    'depth': 1,
    'name': 'JAPANESE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 166,
    'left': 900014,
    'right': 901014,
    'depth': 2,
    'name': 'GENERAL_JAPANESE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 167,
    'left': 901015,
    'right': 902015,
    'depth': 2,
    'name': 'BUSINESS_JAPANESE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 168,
    'left': 902016,
    'right': 903016,
    'depth': 2,
    'name': 'ACADEMIC_JAPANESE',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 169,
    'left': 903017,
    'right': 904017,
    'depth': 2,
    'name': 'EXAM_PREPARATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 170,
    'left': 904018,
    'right': 905018,
    'depth': 2,
    'name': 'UNIVERSITY_PATHWAY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 171,
    'left': 905019,
    'right': 906019,
    'depth': 2,
    'name': 'TEACHER_TRAINING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 172,
    'left': 906020,
    'right': 907020,
    'depth': 2,
    'name': 'WORK_AND_STUDY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 173,
    'left': 907021,
    'right': 908021,
    'depth': 2,
    'name': 'JAPANESE_PLUS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 174,
    'left': 908022,
    'right': 909022,
    'depth': 2,
    'name': 'JUNIOR_PROGRAM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 175,
    'left': 909023,
    'right': 910023,
    'depth': 2,
    'name': 'MATURE_LEARNER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 176,
    'left': 12300027,
    'right': 12400027,
    'depth': 1,
    'name': 'COMMUNITY_SERVICES',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 177,
    'left': 10705018,
    'right': 10706018,
    'depth': 2,
    'name': 'MARKETING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 178,
    'left': 10706019,
    'right': 10707019,
    'depth': 2,
    'name': 'RETAIL_MANAGEMENT',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 179,
    'left': 11109026,
    'right': 11110026,
    'depth': 2,
    'name': 'PRINTING_AND_GRAPHIC_ARTS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 180,
    'left': 12400028,
    'right': 12500028,
    'depth': 1,
    'name': 'INTERNSHIP',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 181,
    'left': 1000013,
    'right': 1100013,
    'depth': 1,
    'name': 'POLISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 182,
    'left': 1000015,
    'right': 1001015,
    'depth': 2,
    'name': 'GENERAL_POLISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 183,
    'left': 1001016,
    'right': 1002016,
    'depth': 2,
    'name': 'BUSINESS_POLISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 184,
    'left': 1002017,
    'right': 1003017,
    'depth': 2,
    'name': 'ACADEMIC_POLISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 185,
    'left': 1003018,
    'right': 1004018,
    'depth': 2,
    'name': 'EXAM_PREPARATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 186,
    'left': 1004019,
    'right': 1005019,
    'depth': 2,
    'name': 'UNIVERSITY_PATHWAY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 187,
    'left': 1005020,
    'right': 1006020,
    'depth': 2,
    'name': 'TEACHER_TRAINING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 188,
    'left': 1006021,
    'right': 1007021,
    'depth': 2,
    'name': 'WORK_AND_STUDY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 189,
    'left': 1007022,
    'right': 1008022,
    'depth': 2,
    'name': 'POLISH_PLUS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 190,
    'left': 1008023,
    'right': 1009023,
    'depth': 2,
    'name': 'JUNIOR_PROGRAM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 191,
    'left': 1009024,
    'right': 1010024,
    'depth': 2,
    'name': 'MATURE_LEARNER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 192,
    'left': 1100014,
    'right': 1200014,
    'depth': 1,
    'name': 'HINDI',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 193,
    'left': 1100016,
    'right': 1101016,
    'depth': 2,
    'name': 'GENERAL_HINDI',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 194,
    'left': 1101017,
    'right': 1102017,
    'depth': 2,
    'name': 'BUSINESS_HINDI',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 195,
    'left': 1102018,
    'right': 1103018,
    'depth': 2,
    'name': 'ACADEMIC_HINDI',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 196,
    'left': 1103019,
    'right': 1104019,
    'depth': 2,
    'name': 'EXAM_PREPARATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 197,
    'left': 1104020,
    'right': 1105020,
    'depth': 2,
    'name': 'UNIVERSITY_PATHWAY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 198,
    'left': 1105021,
    'right': 1106021,
    'depth': 2,
    'name': 'TEACHER_TRAINING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 199,
    'left': 1106022,
    'right': 1107022,
    'depth': 2,
    'name': 'WORK_AND_STUDY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 200,
    'left': 1107023,
    'right': 1108023,
    'depth': 2,
    'name': 'HINDI_PLUS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 201,
    'left': 1108024,
    'right': 1109024,
    'depth': 2,
    'name': 'JUNIOR_PROGRAM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 202,
    'left': 1109025,
    'right': 1110025,
    'depth': 2,
    'name': 'MATURE_LEARNER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 203,
    'left': 1200015,
    'right': 1300015,
    'depth': 1,
    'name': 'ARABIC',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 204,
    'left': 1200017,
    'right': 1201017,
    'depth': 2,
    'name': 'GENERAL_ARABIC',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 205,
    'left': 1201018,
    'right': 1202018,
    'depth': 2,
    'name': 'BUSINESS_ARABIC',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 206,
    'left': 1202019,
    'right': 1203019,
    'depth': 2,
    'name': 'ACADEMIC_ARABIC',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 207,
    'left': 1203020,
    'right': 1204020,
    'depth': 2,
    'name': 'EXAM_PREPARATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 208,
    'left': 1204021,
    'right': 1205021,
    'depth': 2,
    'name': 'UNIVERSITY_PATHWAY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 209,
    'left': 1205022,
    'right': 1206022,
    'depth': 2,
    'name': 'TEACHER_TRAINING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 210,
    'left': 1206023,
    'right': 1207023,
    'depth': 2,
    'name': 'WORK_AND_STUDY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 211,
    'left': 1207024,
    'right': 1208024,
    'depth': 2,
    'name': 'ARABIC_PLUS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 212,
    'left': 1208025,
    'right': 1209025,
    'depth': 2,
    'name': 'JUNIOR_PROGRAM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 213,
    'left': 1209026,
    'right': 1210026,
    'depth': 2,
    'name': 'MATURE_LEARNER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 214,
    'left': 1300016,
    'right': 1400016,
    'depth': 1,
    'name': 'DUTCH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 215,
    'left': 1300018,
    'right': 1301018,
    'depth': 2,
    'name': 'GENERAL_DUTCH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 216,
    'left': 1301019,
    'right': 1302019,
    'depth': 2,
    'name': 'BUSINESS_DUTCH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 217,
    'left': 1302020,
    'right': 1303020,
    'depth': 2,
    'name': 'ACADEMIC_DUTCH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 218,
    'left': 1303021,
    'right': 1304021,
    'depth': 2,
    'name': 'EXAM_PREPARATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 219,
    'left': 1304022,
    'right': 1305022,
    'depth': 2,
    'name': 'UNIVERSITY_PATHWAY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 220,
    'left': 1305023,
    'right': 1306023,
    'depth': 2,
    'name': 'TEACHER_TRAINING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 221,
    'left': 1306024,
    'right': 1307024,
    'depth': 2,
    'name': 'WORK_AND_STUDY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 222,
    'left': 1307025,
    'right': 1308025,
    'depth': 2,
    'name': 'DUTCH_PLUS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 223,
    'left': 1308026,
    'right': 1309026,
    'depth': 2,
    'name': 'JUNIOR_PROGRAM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 224,
    'left': 1309027,
    'right': 1310027,
    'depth': 2,
    'name': 'MATURE_LEARNER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 225,
    'left': 1400017,
    'right': 1500017,
    'depth': 1,
    'name': 'SWEDISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 226,
    'left': 1400019,
    'right': 1401019,
    'depth': 2,
    'name': 'GENERAL_SWEDISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 227,
    'left': 1401020,
    'right': 1402020,
    'depth': 2,
    'name': 'BUSINESS_SWEDISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 228,
    'left': 1402021,
    'right': 1403021,
    'depth': 2,
    'name': 'ACADEMIC_SWEDISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 229,
    'left': 1403022,
    'right': 1404022,
    'depth': 2,
    'name': 'EXAM_PREPARATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 230,
    'left': 1404023,
    'right': 1405023,
    'depth': 2,
    'name': 'UNIVERSITY_PATHWAY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 231,
    'left': 1405024,
    'right': 1406024,
    'depth': 2,
    'name': 'TEACHER_TRAINING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 232,
    'left': 1406025,
    'right': 1407025,
    'depth': 2,
    'name': 'WORK_AND_STUDY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 233,
    'left': 1407026,
    'right': 1408026,
    'depth': 2,
    'name': 'SWEDISH_PLUS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 234,
    'left': 1408027,
    'right': 1409027,
    'depth': 2,
    'name': 'JUNIOR_PROGRAM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 235,
    'left': 1409028,
    'right': 1410028,
    'depth': 2,
    'name': 'MATURE_LEARNER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 236,
    'left': 1500020,
    'right': 1501020,
    'depth': 2,
    'name': 'GENERAL_FINNISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 237,
    'left': 1501021,
    'right': 1502021,
    'depth': 2,
    'name': 'BUSINESS_FINNISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 238,
    'left': 1502022,
    'right': 1503022,
    'depth': 2,
    'name': 'ACADEMIC_FINNISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 239,
    'left': 1503023,
    'right': 1504023,
    'depth': 2,
    'name': 'EXAM_PREPARATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 240,
    'left': 1504024,
    'right': 1505024,
    'depth': 2,
    'name': 'UNIVERSITY_PATHWAY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 241,
    'left': 1505025,
    'right': 1506025,
    'depth': 2,
    'name': 'TEACHER_TRAINING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 242,
    'left': 1506026,
    'right': 1507026,
    'depth': 2,
    'name': 'WORK_AND_STUDY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 243,
    'left': 1507027,
    'right': 1508027,
    'depth': 2,
    'name': 'FINNISH_PLUS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 244,
    'left': 1508028,
    'right': 1509028,
    'depth': 2,
    'name': 'JUNIOR_PROGRAM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 245,
    'left': 1509029,
    'right': 1510029,
    'depth': 2,
    'name': 'MATURE_LEARNER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 246,
    'left': 1500018,
    'right': 1600018,
    'depth': 1,
    'name': 'FINNISH',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 247,
    'left': 1600021,
    'right': 1601021,
    'depth': 2,
    'name': 'GENERAL_NORWEGIAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 248,
    'left': 1601022,
    'right': 1602022,
    'depth': 2,
    'name': 'BUSINESS_NORWEGIAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 249,
    'left': 1602023,
    'right': 1603023,
    'depth': 2,
    'name': 'ACADEMIC_NORWEGIAN',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 250,
    'left': 1603024,
    'right': 1604024,
    'depth': 2,
    'name': 'EXAM_PREPARATION',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 251,
    'left': 1604025,
    'right': 1605025,
    'depth': 2,
    'name': 'UNIVERSITY_PATHWAY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 252,
    'left': 1605026,
    'right': 1606026,
    'depth': 2,
    'name': 'TEACHER_TRAINING',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 253,
    'left': 1606027,
    'right': 1607027,
    'depth': 2,
    'name': 'WORK_AND_STUDY',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 254,
    'left': 1607028,
    'right': 1608028,
    'depth': 2,
    'name': 'NORWEGIAN_PLUS',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 255,
    'left': 1608029,
    'right': 1609029,
    'depth': 2,
    'name': 'JUNIOR_PROGRAM',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 256,
    'left': 1609030,
    'right': 1610030,
    'depth': 2,
    'name': 'MATURE_LEARNER',
    '__typename': 'OfferingCourseCategory',
  },
  {
    'id': 257,
    'left': 1600019,
    'right': 1700019,
    'depth': 1,
    'name': 'NORWEGIAN',
    '__typename': 'OfferingCourseCategory',
  },
]

export const parsedCourseCategories = [
  {
    'id': 1,
    'name': 'LANGUAGES',
    'left': 1,
    'right': 10000001,
    'depth': 0,
    'children': [
      {
        'id': 2,
        'name': 'ENGLISH',
        'left': 3,
        'right': 100003,
        'depth': 1,
        'children': [
          {
            'id': 3,
            'name': 'GENERAL_ENGLISH',
            'left': 5,
            'right': 1005,
            'depth': 2,
            'children': [],
          },
          {
            'id': 4,
            'name': 'BUSINESS_ENGLISH',
            'left': 1006,
            'right': 2006,
            'depth': 2,
            'children': [],
          },
          {
            'id': 5,
            'name': 'ACADEMIC_ENGLISH',
            'left': 2007,
            'right': 3007,
            'depth': 2,
            'children': [],
          },
          {
            'id': 6,
            'name': 'EXAM_PREPARATION',
            'left': 3008,
            'right': 4008,
            'depth': 2,
            'children': [],
          },
          {
            'id': 7,
            'name': 'PROFESSIONAL_AND_EXECUTIVE',
            'left': 4009,
            'right': 5009,
            'depth': 2,
            'children': [],
          },
          {
            'id': 8,
            'name': 'TEACHER_TRAINING',
            'left': 5010,
            'right': 6010,
            'depth': 2,
            'children': [],
          },
          {
            'id': 9,
            'name': 'WORK_AND_STUDY',
            'left': 6011,
            'right': 7011,
            'depth': 2,
            'children': [],
          },
          {
            'id': 10,
            'name': 'ENGLISH_PLUS',
            'left': 7012,
            'right': 8012,
            'depth': 2,
            'children': [],
          },
          {
            'id': 11,
            'name': 'JUNIOR_PROGRAM',
            'left': 8013,
            'right': 9013,
            'depth': 2,
            'children': [],
          },
          {
            'id': 85,
            'name': 'MATURE_LEARNER',
            'left': 9014,
            'right': 10014,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 12,
        'name': 'SPANISH',
        'left': 100004,
        'right': 200004,
        'depth': 1,
        'children': [
          {
            'id': 21,
            'name': 'GENERAL_SPANISH',
            'left': 100006,
            'right': 101006,
            'depth': 2,
            'children': [],
          },
          {
            'id': 22,
            'name': 'BUSINESS_SPANISH',
            'left': 101007,
            'right': 102007,
            'depth': 2,
            'children': [],
          },
          {
            'id': 23,
            'name': 'ACADEMIC_SPANISH',
            'left': 102008,
            'right': 103008,
            'depth': 2,
            'children': [],
          },
          {
            'id': 24,
            'name': 'EXAM_PREPARATION',
            'left': 103009,
            'right': 104009,
            'depth': 2,
            'children': [],
          },
          {
            'id': 25,
            'name': 'PROFESSIONAL_AND_EXECUTIVE',
            'left': 104010,
            'right': 105010,
            'depth': 2,
            'children': [],
          },
          {
            'id': 26,
            'name': 'TEACHER_TRAINING',
            'left': 105011,
            'right': 106011,
            'depth': 2,
            'children': [],
          },
          {
            'id': 27,
            'name': 'WORK_AND_STUDY',
            'left': 106012,
            'right': 107012,
            'depth': 2,
            'children': [],
          },
          {
            'id': 28,
            'name': 'SPANISH_PLUS',
            'left': 107013,
            'right': 108013,
            'depth': 2,
            'children': [],
          },
          {
            'id': 29,
            'name': 'JUNIOR_PROGRAM',
            'left': 108014,
            'right': 109014,
            'depth': 2,
            'children': [],
          },
          {
            'id': 86,
            'name': 'MATURE_LEARNER',
            'left': 109015,
            'right': 110015,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 13,
        'name': 'CHINESE',
        'left': 200005,
        'right': 300005,
        'depth': 1,
        'children': [
          {
            'id': 30,
            'name': 'GENERAL_CHINESE',
            'left': 200007,
            'right': 201007,
            'depth': 2,
            'children': [],
          },
          {
            'id': 31,
            'name': 'BUSINESS_CHINESE',
            'left': 201008,
            'right': 202008,
            'depth': 2,
            'children': [],
          },
          {
            'id': 32,
            'name': 'ACADEMIC_CHINESE',
            'left': 202009,
            'right': 203009,
            'depth': 2,
            'children': [],
          },
          {
            'id': 33,
            'name': 'EXAM_PREPARATION',
            'left': 203010,
            'right': 204010,
            'depth': 2,
            'children': [],
          },
          {
            'id': 34,
            'name': 'PROFESSIONAL_AND_EXECUTIVE',
            'left': 204011,
            'right': 205011,
            'depth': 2,
            'children': [],
          },
          {
            'id': 35,
            'name': 'TEACHER_TRAINING',
            'left': 205012,
            'right': 206012,
            'depth': 2,
            'children': [],
          },
          {
            'id': 36,
            'name': 'WORK_AND_STUDY',
            'left': 206013,
            'right': 207013,
            'depth': 2,
            'children': [],
          },
          {
            'id': 37,
            'name': 'CHINESE_PLUS',
            'left': 207014,
            'right': 208014,
            'depth': 2,
            'children': [],
          },
          {
            'id': 38,
            'name': 'JUNIOR_PROGRAM',
            'left': 208015,
            'right': 209015,
            'depth': 2,
            'children': [],
          },
          {
            'id': 87,
            'name': 'MATURE_LEARNER',
            'left': 209016,
            'right': 210016,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 39,
        'name': 'FRENCH',
        'left': 300006,
        'right': 400006,
        'depth': 1,
        'children': [
          {
            'id': 40,
            'name': 'GENERAL_FRENCH',
            'left': 300008,
            'right': 301008,
            'depth': 2,
            'children': [],
          },
          {
            'id': 41,
            'name': 'BUSINESS_FRENCH',
            'left': 301009,
            'right': 302009,
            'depth': 2,
            'children': [],
          },
          {
            'id': 42,
            'name': 'ACADEMIC_FRENCH',
            'left': 302010,
            'right': 303010,
            'depth': 2,
            'children': [],
          },
          {
            'id': 43,
            'name': 'EXAM_PREPARATION',
            'left': 303011,
            'right': 304011,
            'depth': 2,
            'children': [],
          },
          {
            'id': 44,
            'name': 'PROFESSIONAL_AND_EXECUTIVE',
            'left': 304012,
            'right': 305012,
            'depth': 2,
            'children': [],
          },
          {
            'id': 45,
            'name': 'TEACHER_TRAINING',
            'left': 305013,
            'right': 306013,
            'depth': 2,
            'children': [],
          },
          {
            'id': 46,
            'name': 'WORK_AND_STUDY',
            'left': 306014,
            'right': 307014,
            'depth': 2,
            'children': [],
          },
          {
            'id': 47,
            'name': 'FRENCH_PLUS',
            'left': 307015,
            'right': 308015,
            'depth': 2,
            'children': [],
          },
          {
            'id': 48,
            'name': 'JUNIOR_PROGRAM',
            'left': 308016,
            'right': 309016,
            'depth': 2,
            'children': [],
          },
          {
            'id': 88,
            'name': 'MATURE_LEARNER',
            'left': 309017,
            'right': 310017,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 49,
        'name': 'GERMAN',
        'left': 400007,
        'right': 500007,
        'depth': 1,
        'children': [
          {
            'id': 50,
            'name': 'GENERAL_GERMAN',
            'left': 400009,
            'right': 401009,
            'depth': 2,
            'children': [],
          },
          {
            'id': 51,
            'name': 'BUSINESS_GERMAN',
            'left': 401010,
            'right': 402010,
            'depth': 2,
            'children': [],
          },
          {
            'id': 52,
            'name': 'ACADEMIC_GERMAN',
            'left': 402011,
            'right': 403011,
            'depth': 2,
            'children': [],
          },
          {
            'id': 53,
            'name': 'EXAM_PREPARATION',
            'left': 403012,
            'right': 404012,
            'depth': 2,
            'children': [],
          },
          {
            'id': 54,
            'name': 'PROFESSIONAL_AND_EXECUTIVE',
            'left': 404013,
            'right': 405013,
            'depth': 2,
            'children': [],
          },
          {
            'id': 55,
            'name': 'TEACHER_TRAINING',
            'left': 405014,
            'right': 406014,
            'depth': 2,
            'children': [],
          },
          {
            'id': 56,
            'name': 'WORK_AND_STUDY',
            'left': 406015,
            'right': 407015,
            'depth': 2,
            'children': [],
          },
          {
            'id': 57,
            'name': 'GERMAN_PLUS',
            'left': 407016,
            'right': 408016,
            'depth': 2,
            'children': [],
          },
          {
            'id': 58,
            'name': 'JUNIOR_PROGRAM',
            'left': 408017,
            'right': 409017,
            'depth': 2,
            'children': [],
          },
          {
            'id': 89,
            'name': 'MATURE_LEARNER',
            'left': 409018,
            'right': 410018,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 59,
        'name': 'ITALIAN',
        'left': 500008,
        'right': 600008,
        'depth': 1,
        'children': [
          {
            'id': 60,
            'name': 'GENERAL_ITALIAN',
            'left': 500010,
            'right': 501010,
            'depth': 2,
            'children': [],
          },
          {
            'id': 61,
            'name': 'BUSINESS_ITALIAN',
            'left': 501011,
            'right': 502011,
            'depth': 2,
            'children': [],
          },
          {
            'id': 62,
            'name': 'ACADEMIC_ITALIAN',
            'left': 502012,
            'right': 503012,
            'depth': 2,
            'children': [],
          },
          {
            'id': 63,
            'name': 'EXAM_PREPARATION',
            'left': 503013,
            'right': 504013,
            'depth': 2,
            'children': [],
          },
          {
            'id': 64,
            'name': 'PROFESSIONAL_AND_EXECUTIVE',
            'left': 504014,
            'right': 505014,
            'depth': 2,
            'children': [],
          },
          {
            'id': 65,
            'name': 'TEACHER_TRAINING',
            'left': 505015,
            'right': 506015,
            'depth': 2,
            'children': [],
          },
          {
            'id': 66,
            'name': 'WORK_AND_STUDY',
            'left': 506016,
            'right': 507016,
            'depth': 2,
            'children': [],
          },
          {
            'id': 67,
            'name': 'ITALIAN_PLUS',
            'left': 507017,
            'right': 508017,
            'depth': 2,
            'children': [],
          },
          {
            'id': 68,
            'name': 'JUNIOR_PROGRAM',
            'left': 508018,
            'right': 509018,
            'depth': 2,
            'children': [],
          },
          {
            'id': 90,
            'name': 'MATURE_LEARNER',
            'left': 509019,
            'right': 510019,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 75,
        'name': 'PORTUGUESE',
        'left': 600009,
        'right': 700009,
        'depth': 1,
        'children': [
          {
            'id': 76,
            'name': 'GENERAL_PORTUGUESE',
            'left': 600011,
            'right': 601011,
            'depth': 2,
            'children': [],
          },
          {
            'id': 77,
            'name': 'BUSINESS_PORTUGUESE',
            'left': 601012,
            'right': 602012,
            'depth': 2,
            'children': [],
          },
          {
            'id': 78,
            'name': 'ACADEMIC_PORTUGUESE',
            'left': 602013,
            'right': 603013,
            'depth': 2,
            'children': [],
          },
          {
            'id': 79,
            'name': 'EXAM_PREPARATION',
            'left': 603014,
            'right': 604014,
            'depth': 2,
            'children': [],
          },
          {
            'id': 80,
            'name': 'PROFESSIONAL_AND_EXECUTIVE',
            'left': 604015,
            'right': 605015,
            'depth': 2,
            'children': [],
          },
          {
            'id': 81,
            'name': 'TEACHER_TRAINING',
            'left': 605016,
            'right': 606016,
            'depth': 2,
            'children': [],
          },
          {
            'id': 82,
            'name': 'WORK_AND_STUDY',
            'left': 606017,
            'right': 607017,
            'depth': 2,
            'children': [],
          },
          {
            'id': 83,
            'name': 'PORTUGUESE_PLUS',
            'left': 607018,
            'right': 608018,
            'depth': 2,
            'children': [],
          },
          {
            'id': 84,
            'name': 'JUNIOR_PROGRAM',
            'left': 608019,
            'right': 609019,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 91,
        'name': 'KOREAN',
        'left': 700010,
        'right': 800010,
        'depth': 1,
        'children': [
          {
            'id': 92,
            'name': 'GENERAL_KOREAN',
            'left': 700012,
            'right': 701012,
            'depth': 2,
            'children': [],
          },
          {
            'id': 93,
            'name': 'BUSINESS_KOREAN',
            'left': 701013,
            'right': 702013,
            'depth': 2,
            'children': [],
          },
          {
            'id': 94,
            'name': 'ACADEMIC_KOREAN',
            'left': 702014,
            'right': 703014,
            'depth': 2,
            'children': [],
          },
          {
            'id': 95,
            'name': 'EXAM_PREPARATION',
            'left': 703015,
            'right': 704015,
            'depth': 2,
            'children': [],
          },
          {
            'id': 96,
            'name': 'PROFESSIONAL_AND_EXECUTIVE',
            'left': 704016,
            'right': 705016,
            'depth': 2,
            'children': [],
          },
          {
            'id': 97,
            'name': 'TEACHER_TRAINING',
            'left': 705017,
            'right': 706017,
            'depth': 2,
            'children': [],
          },
          {
            'id': 98,
            'name': 'WORK_AND_STUDY',
            'left': 706018,
            'right': 707018,
            'depth': 2,
            'children': [],
          },
          {
            'id': 99,
            'name': 'KOREAN_PLUS',
            'left': 707019,
            'right': 708019,
            'depth': 2,
            'children': [],
          },
          {
            'id': 100,
            'name': 'JUNIOR_PROGRAM',
            'left': 708020,
            'right': 709020,
            'depth': 2,
            'children': [],
          },
          {
            'id': 101,
            'name': 'MATURE_LEARNER',
            'left': 709021,
            'right': 710021,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 154,
        'name': 'RUSSIAN',
        'left': 800011,
        'right': 900011,
        'depth': 1,
        'children': [
          {
            'id': 155,
            'name': 'GENERAL_RUSSIAN',
            'left': 800013,
            'right': 801013,
            'depth': 2,
            'children': [],
          },
          {
            'id': 156,
            'name': 'BUSINESS_RUSSIAN',
            'left': 801014,
            'right': 802014,
            'depth': 2,
            'children': [],
          },
          {
            'id': 157,
            'name': 'ACADEMIC_RUSSIAN',
            'left': 802015,
            'right': 803015,
            'depth': 2,
            'children': [],
          },
          {
            'id': 158,
            'name': 'EXAM_PREPARATION',
            'left': 803016,
            'right': 804016,
            'depth': 2,
            'children': [],
          },
          {
            'id': 159,
            'name': 'UNIVERSITY_PATHWAY',
            'left': 804017,
            'right': 805017,
            'depth': 2,
            'children': [],
          },
          {
            'id': 160,
            'name': 'TEACHER_TRAINING',
            'left': 805018,
            'right': 806018,
            'depth': 2,
            'children': [],
          },
          {
            'id': 161,
            'name': 'WORK_AND_STUDY',
            'left': 806019,
            'right': 807019,
            'depth': 2,
            'children': [],
          },
          {
            'id': 162,
            'name': 'RUSSIAN_PLUS',
            'left': 807020,
            'right': 808020,
            'depth': 2,
            'children': [],
          },
          {
            'id': 163,
            'name': 'JUNIOR_PROGRAM',
            'left': 808021,
            'right': 809021,
            'depth': 2,
            'children': [],
          },
          {
            'id': 164,
            'name': 'MATURE_LEARNER',
            'left': 809022,
            'right': 810022,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 165,
        'name': 'JAPANESE',
        'left': 900012,
        'right': 1000012,
        'depth': 1,
        'children': [
          {
            'id': 166,
            'name': 'GENERAL_JAPANESE',
            'left': 900014,
            'right': 901014,
            'depth': 2,
            'children': [],
          },
          {
            'id': 167,
            'name': 'BUSINESS_JAPANESE',
            'left': 901015,
            'right': 902015,
            'depth': 2,
            'children': [],
          },
          {
            'id': 168,
            'name': 'ACADEMIC_JAPANESE',
            'left': 902016,
            'right': 903016,
            'depth': 2,
            'children': [],
          },
          {
            'id': 169,
            'name': 'EXAM_PREPARATION',
            'left': 903017,
            'right': 904017,
            'depth': 2,
            'children': [],
          },
          {
            'id': 170,
            'name': 'UNIVERSITY_PATHWAY',
            'left': 904018,
            'right': 905018,
            'depth': 2,
            'children': [],
          },
          {
            'id': 171,
            'name': 'TEACHER_TRAINING',
            'left': 905019,
            'right': 906019,
            'depth': 2,
            'children': [],
          },
          {
            'id': 172,
            'name': 'WORK_AND_STUDY',
            'left': 906020,
            'right': 907020,
            'depth': 2,
            'children': [],
          },
          {
            'id': 173,
            'name': 'JAPANESE_PLUS',
            'left': 907021,
            'right': 908021,
            'depth': 2,
            'children': [],
          },
          {
            'id': 174,
            'name': 'JUNIOR_PROGRAM',
            'left': 908022,
            'right': 909022,
            'depth': 2,
            'children': [],
          },
          {
            'id': 175,
            'name': 'MATURE_LEARNER',
            'left': 909023,
            'right': 910023,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 181,
        'name': 'POLISH',
        'left': 1000013,
        'right': 1100013,
        'depth': 1,
        'children': [
          {
            'id': 182,
            'name': 'GENERAL_POLISH',
            'left': 1000015,
            'right': 1001015,
            'depth': 2,
            'children': [],
          },
          {
            'id': 183,
            'name': 'BUSINESS_POLISH',
            'left': 1001016,
            'right': 1002016,
            'depth': 2,
            'children': [],
          },
          {
            'id': 184,
            'name': 'ACADEMIC_POLISH',
            'left': 1002017,
            'right': 1003017,
            'depth': 2,
            'children': [],
          },
          {
            'id': 185,
            'name': 'EXAM_PREPARATION',
            'left': 1003018,
            'right': 1004018,
            'depth': 2,
            'children': [],
          },
          {
            'id': 186,
            'name': 'UNIVERSITY_PATHWAY',
            'left': 1004019,
            'right': 1005019,
            'depth': 2,
            'children': [],
          },
          {
            'id': 187,
            'name': 'TEACHER_TRAINING',
            'left': 1005020,
            'right': 1006020,
            'depth': 2,
            'children': [],
          },
          {
            'id': 188,
            'name': 'WORK_AND_STUDY',
            'left': 1006021,
            'right': 1007021,
            'depth': 2,
            'children': [],
          },
          {
            'id': 189,
            'name': 'POLISH_PLUS',
            'left': 1007022,
            'right': 1008022,
            'depth': 2,
            'children': [],
          },
          {
            'id': 190,
            'name': 'JUNIOR_PROGRAM',
            'left': 1008023,
            'right': 1009023,
            'depth': 2,
            'children': [],
          },
          {
            'id': 191,
            'name': 'MATURE_LEARNER',
            'left': 1009024,
            'right': 1010024,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 192,
        'name': 'HINDI',
        'left': 1100014,
        'right': 1200014,
        'depth': 1,
        'children': [
          {
            'id': 193,
            'name': 'GENERAL_HINDI',
            'left': 1100016,
            'right': 1101016,
            'depth': 2,
            'children': [],
          },
          {
            'id': 194,
            'name': 'BUSINESS_HINDI',
            'left': 1101017,
            'right': 1102017,
            'depth': 2,
            'children': [],
          },
          {
            'id': 195,
            'name': 'ACADEMIC_HINDI',
            'left': 1102018,
            'right': 1103018,
            'depth': 2,
            'children': [],
          },
          {
            'id': 196,
            'name': 'EXAM_PREPARATION',
            'left': 1103019,
            'right': 1104019,
            'depth': 2,
            'children': [],
          },
          {
            'id': 197,
            'name': 'UNIVERSITY_PATHWAY',
            'left': 1104020,
            'right': 1105020,
            'depth': 2,
            'children': [],
          },
          {
            'id': 198,
            'name': 'TEACHER_TRAINING',
            'left': 1105021,
            'right': 1106021,
            'depth': 2,
            'children': [],
          },
          {
            'id': 199,
            'name': 'WORK_AND_STUDY',
            'left': 1106022,
            'right': 1107022,
            'depth': 2,
            'children': [],
          },
          {
            'id': 200,
            'name': 'HINDI_PLUS',
            'left': 1107023,
            'right': 1108023,
            'depth': 2,
            'children': [],
          },
          {
            'id': 201,
            'name': 'JUNIOR_PROGRAM',
            'left': 1108024,
            'right': 1109024,
            'depth': 2,
            'children': [],
          },
          {
            'id': 202,
            'name': 'MATURE_LEARNER',
            'left': 1109025,
            'right': 1110025,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 203,
        'name': 'ARABIC',
        'left': 1200015,
        'right': 1300015,
        'depth': 1,
        'children': [
          {
            'id': 204,
            'name': 'GENERAL_ARABIC',
            'left': 1200017,
            'right': 1201017,
            'depth': 2,
            'children': [],
          },
          {
            'id': 205,
            'name': 'BUSINESS_ARABIC',
            'left': 1201018,
            'right': 1202018,
            'depth': 2,
            'children': [],
          },
          {
            'id': 206,
            'name': 'ACADEMIC_ARABIC',
            'left': 1202019,
            'right': 1203019,
            'depth': 2,
            'children': [],
          },
          {
            'id': 207,
            'name': 'EXAM_PREPARATION',
            'left': 1203020,
            'right': 1204020,
            'depth': 2,
            'children': [],
          },
          {
            'id': 208,
            'name': 'UNIVERSITY_PATHWAY',
            'left': 1204021,
            'right': 1205021,
            'depth': 2,
            'children': [],
          },
          {
            'id': 209,
            'name': 'TEACHER_TRAINING',
            'left': 1205022,
            'right': 1206022,
            'depth': 2,
            'children': [],
          },
          {
            'id': 210,
            'name': 'WORK_AND_STUDY',
            'left': 1206023,
            'right': 1207023,
            'depth': 2,
            'children': [],
          },
          {
            'id': 211,
            'name': 'ARABIC_PLUS',
            'left': 1207024,
            'right': 1208024,
            'depth': 2,
            'children': [],
          },
          {
            'id': 212,
            'name': 'JUNIOR_PROGRAM',
            'left': 1208025,
            'right': 1209025,
            'depth': 2,
            'children': [],
          },
          {
            'id': 213,
            'name': 'MATURE_LEARNER',
            'left': 1209026,
            'right': 1210026,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 214,
        'name': 'DUTCH',
        'left': 1300016,
        'right': 1400016,
        'depth': 1,
        'children': [
          {
            'id': 215,
            'name': 'GENERAL_DUTCH',
            'left': 1300018,
            'right': 1301018,
            'depth': 2,
            'children': [],
          },
          {
            'id': 216,
            'name': 'BUSINESS_DUTCH',
            'left': 1301019,
            'right': 1302019,
            'depth': 2,
            'children': [],
          },
          {
            'id': 217,
            'name': 'ACADEMIC_DUTCH',
            'left': 1302020,
            'right': 1303020,
            'depth': 2,
            'children': [],
          },
          {
            'id': 218,
            'name': 'EXAM_PREPARATION',
            'left': 1303021,
            'right': 1304021,
            'depth': 2,
            'children': [],
          },
          {
            'id': 219,
            'name': 'UNIVERSITY_PATHWAY',
            'left': 1304022,
            'right': 1305022,
            'depth': 2,
            'children': [],
          },
          {
            'id': 220,
            'name': 'TEACHER_TRAINING',
            'left': 1305023,
            'right': 1306023,
            'depth': 2,
            'children': [],
          },
          {
            'id': 221,
            'name': 'WORK_AND_STUDY',
            'left': 1306024,
            'right': 1307024,
            'depth': 2,
            'children': [],
          },
          {
            'id': 222,
            'name': 'DUTCH_PLUS',
            'left': 1307025,
            'right': 1308025,
            'depth': 2,
            'children': [],
          },
          {
            'id': 223,
            'name': 'JUNIOR_PROGRAM',
            'left': 1308026,
            'right': 1309026,
            'depth': 2,
            'children': [],
          },
          {
            'id': 224,
            'name': 'MATURE_LEARNER',
            'left': 1309027,
            'right': 1310027,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 225,
        'name': 'SWEDISH',
        'left': 1400017,
        'right': 1500017,
        'depth': 1,
        'children': [
          {
            'id': 226,
            'name': 'GENERAL_SWEDISH',
            'left': 1400019,
            'right': 1401019,
            'depth': 2,
            'children': [],
          },
          {
            'id': 227,
            'name': 'BUSINESS_SWEDISH',
            'left': 1401020,
            'right': 1402020,
            'depth': 2,
            'children': [],
          },
          {
            'id': 228,
            'name': 'ACADEMIC_SWEDISH',
            'left': 1402021,
            'right': 1403021,
            'depth': 2,
            'children': [],
          },
          {
            'id': 229,
            'name': 'EXAM_PREPARATION',
            'left': 1403022,
            'right': 1404022,
            'depth': 2,
            'children': [],
          },
          {
            'id': 230,
            'name': 'UNIVERSITY_PATHWAY',
            'left': 1404023,
            'right': 1405023,
            'depth': 2,
            'children': [],
          },
          {
            'id': 231,
            'name': 'TEACHER_TRAINING',
            'left': 1405024,
            'right': 1406024,
            'depth': 2,
            'children': [],
          },
          {
            'id': 232,
            'name': 'WORK_AND_STUDY',
            'left': 1406025,
            'right': 1407025,
            'depth': 2,
            'children': [],
          },
          {
            'id': 233,
            'name': 'SWEDISH_PLUS',
            'left': 1407026,
            'right': 1408026,
            'depth': 2,
            'children': [],
          },
          {
            'id': 234,
            'name': 'JUNIOR_PROGRAM',
            'left': 1408027,
            'right': 1409027,
            'depth': 2,
            'children': [],
          },
          {
            'id': 235,
            'name': 'MATURE_LEARNER',
            'left': 1409028,
            'right': 1410028,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 246,
        'name': 'FINNISH',
        'left': 1500018,
        'right': 1600018,
        'depth': 1,
        'children': [
          {
            'id': 236,
            'name': 'GENERAL_FINNISH',
            'left': 1500020,
            'right': 1501020,
            'depth': 2,
            'children': [],
          },
          {
            'id': 237,
            'name': 'BUSINESS_FINNISH',
            'left': 1501021,
            'right': 1502021,
            'depth': 2,
            'children': [],
          },
          {
            'id': 238,
            'name': 'ACADEMIC_FINNISH',
            'left': 1502022,
            'right': 1503022,
            'depth': 2,
            'children': [],
          },
          {
            'id': 239,
            'name': 'EXAM_PREPARATION',
            'left': 1503023,
            'right': 1504023,
            'depth': 2,
            'children': [],
          },
          {
            'id': 240,
            'name': 'UNIVERSITY_PATHWAY',
            'left': 1504024,
            'right': 1505024,
            'depth': 2,
            'children': [],
          },
          {
            'id': 241,
            'name': 'TEACHER_TRAINING',
            'left': 1505025,
            'right': 1506025,
            'depth': 2,
            'children': [],
          },
          {
            'id': 242,
            'name': 'WORK_AND_STUDY',
            'left': 1506026,
            'right': 1507026,
            'depth': 2,
            'children': [],
          },
          {
            'id': 243,
            'name': 'FINNISH_PLUS',
            'left': 1507027,
            'right': 1508027,
            'depth': 2,
            'children': [],
          },
          {
            'id': 244,
            'name': 'JUNIOR_PROGRAM',
            'left': 1508028,
            'right': 1509028,
            'depth': 2,
            'children': [],
          },
          {
            'id': 245,
            'name': 'MATURE_LEARNER',
            'left': 1509029,
            'right': 1510029,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 257,
        'name': 'NORWEGIAN',
        'left': 1600019,
        'right': 1700019,
        'depth': 1,
        'children': [
          {
            'id': 247,
            'name': 'GENERAL_NORWEGIAN',
            'left': 1600021,
            'right': 1601021,
            'depth': 2,
            'children': [],
          },
          {
            'id': 248,
            'name': 'BUSINESS_NORWEGIAN',
            'left': 1601022,
            'right': 1602022,
            'depth': 2,
            'children': [],
          },
          {
            'id': 249,
            'name': 'ACADEMIC_NORWEGIAN',
            'left': 1602023,
            'right': 1603023,
            'depth': 2,
            'children': [],
          },
          {
            'id': 250,
            'name': 'EXAM_PREPARATION',
            'left': 1603024,
            'right': 1604024,
            'depth': 2,
            'children': [],
          },
          {
            'id': 251,
            'name': 'UNIVERSITY_PATHWAY',
            'left': 1604025,
            'right': 1605025,
            'depth': 2,
            'children': [],
          },
          {
            'id': 252,
            'name': 'TEACHER_TRAINING',
            'left': 1605026,
            'right': 1606026,
            'depth': 2,
            'children': [],
          },
          {
            'id': 253,
            'name': 'WORK_AND_STUDY',
            'left': 1606027,
            'right': 1607027,
            'depth': 2,
            'children': [],
          },
          {
            'id': 254,
            'name': 'NORWEGIAN_PLUS',
            'left': 1607028,
            'right': 1608028,
            'depth': 2,
            'children': [],
          },
          {
            'id': 255,
            'name': 'JUNIOR_PROGRAM',
            'left': 1608029,
            'right': 1609029,
            'depth': 2,
            'children': [],
          },
          {
            'id': 256,
            'name': 'MATURE_LEARNER',
            'left': 1609030,
            'right': 1610030,
            'depth': 2,
            'children': [],
          },
        ],
      },
    ],
  },
  {
    'id': 14,
    'name': 'VOCATIONAL',
    'left': 10000002,
    'right': 20000002,
    'depth': 0,
    'children': [
      {
        'id': 102,
        'name': 'AVIATION',
        'left': 10000004,
        'right': 10100004,
        'depth': 1,
        'children': [],
      },
      {
        'id': 103,
        'name': 'ACCOUNTING',
        'left': 10100005,
        'right': 10200005,
        'depth': 1,
        'children': [],
      },
      {
        'id': 104,
        'name': 'AGED_CARE',
        'left': 10200006,
        'right': 10300006,
        'depth': 1,
        'children': [],
      },
      {
        'id': 105,
        'name': 'AMC_CLINICAL_AND_PESCI_PREP',
        'left': 10300007,
        'right': 10400007,
        'depth': 1,
        'children': [],
      },
      {
        'id': 106,
        'name': 'ANIMAL_CARE',
        'left': 10400008,
        'right': 10500008,
        'depth': 1,
        'children': [],
      },
      {
        'id': 107,
        'name': 'AUTOMOTIVE_STUDIES',
        'left': 10500009,
        'right': 10600009,
        'depth': 1,
        'children': [],
      },
      {
        'id': 108,
        'name': 'SCIENCE_AND_ENGINEERING',
        'left': 10600010,
        'right': 10700010,
        'depth': 1,
        'children': [
          {
            'id': 109,
            'name': 'BUILDING_CONSTRUCTION',
            'left': 10600012,
            'right': 10601012,
            'depth': 2,
            'children': [],
          },
          {
            'id': 110,
            'name': 'ENGINEERING_STUDIES',
            'left': 10601013,
            'right': 10602013,
            'depth': 2,
            'children': [],
          },
          {
            'id': 111,
            'name': 'ENVIRONMENTAL_SCIENCES',
            'left': 10602014,
            'right': 10603014,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 112,
        'name': 'BUSINESS_MANAGEMENT',
        'left': 10700011,
        'right': 10800011,
        'depth': 1,
        'children': [
          {
            'id': 113,
            'name': 'MARKETING_AND_ADVERTISING',
            'left': 10701014,
            'right': 10702014,
            'depth': 2,
            'children': [],
          },
          {
            'id': 114,
            'name': 'FINANCE',
            'left': 10702015,
            'right': 10703015,
            'depth': 2,
            'children': [],
          },
          {
            'id': 149,
            'name': 'PROJECT_MANAGEMENT',
            'left': 10703016,
            'right': 10704016,
            'depth': 2,
            'children': [],
          },
          {
            'id': 150,
            'name': 'LEADERSHIP_AND_MANAGEMENT',
            'left': 10704017,
            'right': 10705017,
            'depth': 2,
            'children': [],
          },
          {
            'id': 151,
            'name': 'BUSINESS',
            'left': 10700013,
            'right': 10701013,
            'depth': 2,
            'children': [],
          },
          {
            'id': 177,
            'name': 'MARKETING',
            'left': 10705018,
            'right': 10706018,
            'depth': 2,
            'children': [],
          },
          {
            'id': 178,
            'name': 'RETAIL_MANAGEMENT',
            'left': 10706019,
            'right': 10707019,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 115,
        'name': 'CHILDREN_SERVICES',
        'left': 10800012,
        'right': 10900012,
        'depth': 1,
        'children': [],
      },
      {
        'id': 116,
        'name': 'HEALTH_SERVICES',
        'left': 10900013,
        'right': 11000013,
        'depth': 1,
        'children': [],
      },
      {
        'id': 117,
        'name': 'HORTICULTURE',
        'left': 11000014,
        'right': 11100014,
        'depth': 1,
        'children': [],
      },
      {
        'id': 118,
        'name': 'ART_DIGITAL_MEDIA_AND_DESIGN',
        'left': 11100015,
        'right': 11200015,
        'depth': 1,
        'children': [
          {
            'id': 119,
            'name': 'FINE_ARTS',
            'left': 11100017,
            'right': 11101017,
            'depth': 2,
            'children': [],
          },
          {
            'id': 120,
            'name': 'DESIGN',
            'left': 11101018,
            'right': 11102018,
            'depth': 2,
            'children': [],
          },
          {
            'id': 121,
            'name': 'GRAPHIC_DESIGN',
            'left': 11102019,
            'right': 11103019,
            'depth': 2,
            'children': [],
          },
          {
            'id': 122,
            'name': 'DIGITAL_MEDIA',
            'left': 11103020,
            'right': 11104020,
            'depth': 2,
            'children': [],
          },
          {
            'id': 123,
            'name': 'PHOTOGRAPHY',
            'left': 11104021,
            'right': 11105021,
            'depth': 2,
            'children': [],
          },
          {
            'id': 124,
            'name': 'INTERIOR_DESIGN',
            'left': 11105022,
            'right': 11106022,
            'depth': 2,
            'children': [],
          },
          {
            'id': 125,
            'name': 'ANIMATION',
            'left': 11106023,
            'right': 11107023,
            'depth': 2,
            'children': [],
          },
          {
            'id': 126,
            'name': 'GAMING',
            'left': 11107024,
            'right': 11108024,
            'depth': 2,
            'children': [],
          },
          {
            'id': 127,
            'name': 'FILM',
            'left': 11108025,
            'right': 11109025,
            'depth': 2,
            'children': [],
          },
          {
            'id': 179,
            'name': 'PRINTING_AND_GRAPHIC_ARTS',
            'left': 11109026,
            'right': 11110026,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 128,
        'name': 'FASHION_AND_BEAUTY',
        'left': 11200016,
        'right': 11300016,
        'depth': 1,
        'children': [
          {
            'id': 129,
            'name': 'FASHION_DESIGN',
            'left': 11200018,
            'right': 11201018,
            'depth': 2,
            'children': [],
          },
          {
            'id': 130,
            'name': 'FASHION_MERCHANDISING',
            'left': 11201019,
            'right': 11202019,
            'depth': 2,
            'children': [],
          },
          {
            'id': 131,
            'name': 'JEWELLERY_DESIGN',
            'left': 11202020,
            'right': 11203020,
            'depth': 2,
            'children': [],
          },
          {
            'id': 132,
            'name': 'BEAUTY_AND_AESTHETICIAN',
            'left': 11203021,
            'right': 11204021,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 133,
        'name': 'HUMAN_RESOURCES',
        'left': 11300017,
        'right': 11400017,
        'depth': 1,
        'children': [],
      },
      {
        'id': 134,
        'name': 'MASSAGE_THERAPY',
        'left': 11400018,
        'right': 11500018,
        'depth': 1,
        'children': [],
      },
      {
        'id': 135,
        'name': 'MUSIC_STUDIES',
        'left': 11500019,
        'right': 11600019,
        'depth': 1,
        'children': [],
      },
      {
        'id': 136,
        'name': 'OCCUPATIONAL_HEALTH_AND_SAFETY',
        'left': 11600020,
        'right': 11700020,
        'depth': 1,
        'children': [],
      },
      {
        'id': 137,
        'name': 'SPORTS_AND_FITNESS',
        'left': 11700021,
        'right': 11800021,
        'depth': 1,
        'children': [],
      },
      {
        'id': 138,
        'name': 'THEOLOGY',
        'left': 11800022,
        'right': 11900022,
        'depth': 1,
        'children': [],
      },
      {
        'id': 139,
        'name': 'HOSPITALITY_AND_TOURISM',
        'left': 11900023,
        'right': 12000023,
        'depth': 1,
        'children': [
          {
            'id': 140,
            'name': 'HOSPITALITY',
            'left': 11900025,
            'right': 11901025,
            'depth': 2,
            'children': [],
          },
          {
            'id': 141,
            'name': 'TOURISM',
            'left': 11901026,
            'right': 11902026,
            'depth': 2,
            'children': [],
          },
          {
            'id': 142,
            'name': 'CULINARY_STUDIES',
            'left': 11902027,
            'right': 11903027,
            'depth': 2,
            'children': [],
          },
          {
            'id': 143,
            'name': 'EVENTS',
            'left': 11903028,
            'right': 11904028,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 144,
        'name': 'TRAINING_ASSESSMENT',
        'left': 12000024,
        'right': 12100024,
        'depth': 1,
        'children': [],
      },
      {
        'id': 145,
        'name': 'TECHNOLOGY',
        'left': 12100025,
        'right': 12200025,
        'depth': 1,
        'children': [
          {
            'id': 146,
            'name': 'INFORMATION_TECHNOLOGY',
            'left': 12100027,
            'right': 12101027,
            'depth': 2,
            'children': [],
          },
          {
            'id': 147,
            'name': 'TELECOMMUNICATIONS',
            'left': 12101028,
            'right': 12102028,
            'depth': 2,
            'children': [],
          },
          {
            'id': 148,
            'name': 'PROGRAMMING',
            'left': 12102029,
            'right': 12103029,
            'depth': 2,
            'children': [],
          },
        ],
      },
      {
        'id': 153,
        'name': 'TRANSLATION_AND_INTERPRETATION',
        'left': 12200026,
        'right': 12300026,
        'depth': 1,
        'children': [],
      },
      {
        'id': 176,
        'name': 'COMMUNITY_SERVICES',
        'left': 12300027,
        'right': 12400027,
        'depth': 1,
        'children': [],
      },
      {
        'id': 180,
        'name': 'INTERNSHIP',
        'left': 12400028,
        'right': 12500028,
        'depth': 1,
        'children': [],
      },
    ],
  },
  {
    'id': 15,
    'name': 'HIGHSCHOOL',
    'left': 20000003,
    'right': 30000003,
    'depth': 0,
    'children': [
      {
        'id': 69,
        'name': 'PUBLIC',
        'left': 20000005,
        'right': 20100005,
        'depth': 1,
        'children': [],
      },
      {
        'id': 70,
        'name': 'PRIVATE',
        'left': 20100006,
        'right': 20200006,
        'depth': 1,
        'children': [],
      },
    ],
  },
  {
    'id': 16,
    'name': 'HIGHER_EDUCATION',
    'left': 30000004,
    'right': 40000004,
    'depth': 0,
    'children': [
      {
        'id': 17,
        'name': 'UNDERGRADUATE',
        'left': 30000006,
        'right': 30100006,
        'depth': 1,
        'children': [],
      },
      {
        'id': 18,
        'name': 'GRADUATE',
        'left': 30100007,
        'right': 30200007,
        'depth': 1,
        'children': [],
      },
      {
        'id': 19,
        'name': 'CERTIFICATE',
        'left': 30200008,
        'right': 30300008,
        'depth': 1,
        'children': [],
      },
      {
        'id': 71,
        'name': 'DIPLOMA',
        'left': 30300009,
        'right': 30400009,
        'depth': 1,
        'children': [],
      },
      {
        'id': 72,
        'name': 'POST_GRADUATE',
        'left': 30400010,
        'right': 30500010,
        'depth': 1,
        'children': [],
      },
      {
        'id': 73,
        'name': 'MASTERS',
        'left': 30500011,
        'right': 30600011,
        'depth': 1,
        'children': [],
      },
      {
        'id': 74,
        'name': 'PHD',
        'left': 30600012,
        'right': 30700012,
        'depth': 1,
        'children': [],
      },
    ],
  },
  {
    'id': 152,
    'name': 'OTHER',
    'left': 40000005,
    'right': 50000005,
    'depth': 0,
    'children': [
      {
        'id': 20,
        'name': 'OTHER',
        'left': 40000007,
        'right': 40100007,
        'depth': 1,
        'children': [],
      },
    ],
  },
]
